import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header/Header'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog PokeApi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
        <Header />
        {children}
        </div>
      </body>
    </html>
  )
}
